apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "<token>"
    apiServerEndpoint: "k8s.sj.ifsc.edu.br:6443"
    caCertHashes:
    - "<sha256>"
controlPlane:
  localAPIEndpoint:
    advertiseAddress: "2804:1454:1004:103::238"
    bindPort: 6443
  certificateKey: "chave-longa-gerada-pelo-upload-certs"
nodeRegistration:
  name: k8s-1.sj.ifsc.edu.br
  kubeletExtraArgs:
  - name: "node-ip"
    value: "2804:1454:1004:103::238,191.36.14.238"
  - name: "resolv-conf"
    value: "/etc/k8s-resolv.conf"
