apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-teste
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-teste
  template:
    metadata:
      labels:
        app: web-teste
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:6.0.0
        ports:
        - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: web-teste-svc
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
  selector:
    app: web-teste
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-central
  namespace: default
  annotations:
    io.cilium/gateway-service-type: "NodePort"
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
  - name: https-tcp
    protocol: HTTPS
    port: 443
    hostname: "*.k8s.sj.ifsc.edu.br"
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - name: wildcard-k8s-ifsc-tls
  - name: https-udp
    protocol: UDP
    port: 443
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rota-aplicacao-um
  namespace: default
spec:
  parentRefs:
  - name: gateway-central
    kind: Gateway
  hostnames:
  - "app1.k8s.sj.ifsc.edu.br"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: "Alt-Svc"
          value: 'h3=":443"; ma=86400'
    backendRefs:
    - name: web-teste-svc
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rota-aplicacao-dois
  namespace: default
spec:
  parentRefs:
  - name: gateway-central
    kind: Gateway
  hostnames:
  - "app2.k8s.sj.ifsc.edu.br"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: "Alt-Svc"
          value: 'h3=":443"; ma=86400'
    backendRefs:
    - name: web-teste-svc
      port: 80