---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  namespace: feira-de-jogos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: feira-de-jogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres
          envFrom:
          - secretRef:
              name: secret-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: feira-de-jogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: ghcr.io/feira-de-jogos/feira-de-jogos/rest-api:latest
          envFrom:
          - secretRef:
              name: secret-rest-api
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-db
  namespace: feira-de-jogos
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: service-rest-api
  namespace: feira-de-jogos
spec:
  selector:
    app: rest-api
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-rest-api
  namespace: feira-de-jogos
spec:
  parentRefs:
    - name: gateway-feira-de-jogos
      sectionName: https-rest-api
  hostnames:
    - "feira-de-jogos.dev.br"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v2
    backendRefs:
    - name: service-rest-api
      port: 3000
