---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-influxdb
  namespace: feira-de-jogos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: feira-de-jogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "feira"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "feira"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-influxdb
                  key: influxdb-username
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-influxdb
                  key: influxdb-password
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-influxdb
                  key: influxdb-admin-token
          ports:
            - containerPort: 8086
          livenessProbe:
            exec:
              command: ["influx", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["influx", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/influxdb2
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: service-influxdb
  namespace: feira-de-jogos
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-influxdb
  namespace: feira-de-jogos
spec:
  parentRefs:
    - name: gateway-feira-de-jogos
      sectionName: https-tsdb
  hostnames:
    - "tsdb.k8s.sj.ifsc.edu.br"
  rules:
    - backendRefs:
        - name: service-influxdb
          port: 8086
